// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Predict_a_numberML.Model
{
    public class ModelInput
    {
        [ColumnName("sentence"), LoadColumn(0)]
        public string Sentence { get; set; }


        [ColumnName("type"), LoadColumn(1)]
        public string Type { get; set; }


    }
}
